# Concatenates the Emscripten glue and the AudioWorklet processor into one
# self-contained script. Run by the build; not meant to be invoked by hand.
file(READ ${GLUE} glue)
file(READ ${PROCESSOR} processor)
file(WRITE ${OUT}
"// Generated by the build - do not edit.
//
// libenginesim AudioWorklet: Emscripten glue with the wasm inlined as base64,
// followed by the processor. Self-contained because AudioWorkletGlobalScope
// has neither fetch() nor import().

// AudioWorkletGlobalScope has no performance object, but upstream's Simulator
// times its frames with std::chrono::steady_clock, which compiles down to
// clock_time_get and then to performance.now(). currentTime is the worklet's
// own monotonic clock, in seconds.
globalThis.performance ??= { now: () => currentTime * 1000 };

${glue}
${processor}
")
